env: 
  browser: true
  node: true
globals: 
  fetch: true
parser: babel-eslint
extends: 
  - eslint:recommended
  - plugin:flowtype/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
  - plugin:react/recommended
